ROBOT1:
  robot_type: "fer"
  arm_prefix: ""
  fake_sensor_commands: "false"
  joint_state_rate: 30
  load_gripper: "false"
  namespace: ""
  robot_ip: "172.16.0.2"
  use_fake_hardware: "false"
  use_rviz: "false"
